export const VEHICLES_CONFIG = [
  {
    id: "AMB-01",
    type: "ambulance" as const,
    label: "Ambulance 01",
    icon: "🚑",
    color: "#06b6d4",
    speed: 48,
    startPos: [21.1458, 79.0882] as [number, number],
    destinationType: "hospital" as const,
    destinationIndex: 0,
    incidentPos: undefined as [number, number] | undefined,
    incidentLabel: undefined as string | undefined,
  },
  {
    id: "AMB-02",
    type: "ambulance" as const,
    label: "Ambulance 02",
    icon: "🚑",
    color: "#a855f7",
    speed: 36,
    startPos: [21.1320, 79.0720] as [number, number],
    destinationType: "hospital" as const,
    destinationIndex: 1,
    incidentPos: undefined as [number, number] | undefined,
    incidentLabel: undefined as string | undefined,
  },
  {
    id: "FIRE-01",
    type: "fire" as const,
    label: "Fire Engine 01",
    icon: "🚒",
    color: "#f97316",
    speed: 42,
    startPos: [21.1540, 79.0900] as [number, number],
    destinationType: "incident" as const,
    destinationIndex: 0,
    incidentPos: [21.1393, 79.0820] as [number, number],
    incidentLabel: "Factory Fire — Sitabuldi Junction",
  },
];

export const SIGNALS_CONFIG = [
  { id: "SIG-A", lat: 21.1451, lng: 79.0888, label: "Sitabuldi Main Rd & Residency Rd" },
  { id: "SIG-B", lat: 21.1490, lng: 79.0825, label: "Central Ave & Maharajbagh Rd" },
  { id: "SIG-C", lat: 21.1372, lng: 79.0848, label: "Wardha Rd & Law College Sq" },
  { id: "SIG-D", lat: 21.1324, lng: 79.0759, label: "Ramdaspeth & Shankar Nagar Sq" },
  { id: "SIG-E", lat: 21.1415, lng: 79.0941, label: "Railway Station Rd & LIC Sq" },
  { id: "SIG-F", lat: 21.1529, lng: 79.0961, label: "CA Rd & Gandhibagh Junction" },
];
